DATA_CONFIG:
    mono: "data/elpv_mono"
    poly: "data/elpv_poly"

MODEL:
    NAME: "ResNet34"
    LAYERS: [3, 4, 6, 3]
    NUM_CLASSES: 2


OPTIMIZATION:
    BATCH_SIZE: 64
    NUM_EPOCHS: 60

    OPTIMIZER: SGD
    LR: 0.006
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    scheduler: Polynomial
    class_weights:
        mono: [1.5236, 2.9097]
        poly: [1.4114, 3.4307]
